void displayLoginRegisterMenu(savefile &account, string filename, PlayerInfo players[], char** title, int title_row, int title_col, bool &run, bool &isLogged, int &choice);
void displayForm(string filename, savefile &account, PlayerInfo players[], int choice, bool &isLogged);
void generateMenu(savefile &account, GameState &game, PlayerInfo players[], string filename, int &page, int &choice, char** title, int title_row, int title_col, bool &run, bool &continue_game, int &word_count, bool &isLogged, string &bg_file);
void displayGameTitle(char** title, int title_row, int title_col);
void displayMainMenu(int choice);
void displayDifficultyChoice(int choice);
void displayCustomBoardPage(GameState game, int choice);
void displayLoadGamePage(savefile account, int choice);
void displayAccountInfo(savefile account);
void displayAccOptions(int choice);
void changeNameForm(savefile &account, string account_file, PlayerInfo players[], bool &changed);
void changePasswordForm(savefile &account, string account_file, bool &changed);
void processHacking(savefile account, int choice);
bool checkCheatCode(char c, int &count, string cheatCode);
void displayCreditPage();
void sortRecord(Record record[], int n);
void displaySavePage(GameState game, savefile account, int choice);
void displayLdBoard(PlayerInfo players[]);